root -l  binShiftSchem.C
root -l  collision.C
root -l  fireball.C
root -l  fluxTubes3.C
root -l  fluxTubes3SAVE.C
root -l  fxnForms.C
root -l  impactPara.C
root -l  init.C
root -l  openingAngle.C
root -l  phaseDiagram.C
root -l  phaseDiagram2.C
root -l  phaseDiagram3.C
root -l  photons.C
root -l  promptGamma_qgp.C
root -l  SchemPhase.C
root -l  spaceTime.C
root -l  TAB.C
root -l  tempTime.C
root -l  thermalGamma_hhg.C
root -l  TwoPanel.C
root -l  TwoPanel_Logy.C
root -l  woodsSaxon.C
